import type { ArtifactRef, SpecOutline, VerificationResult } from "../types";
import { saveArtifactFile } from "../artifacts";

export async function runDemoVerification(
  sessionId: string,
  spec: SpecOutline
): Promise<{ artifact: ArtifactRef; verification: VerificationResult[] }> {
  const html = generateDemoHtml(spec);

  const artifact = saveArtifactFile(
    sessionId,
    "index.html",
    html,
    "demo",
    "text/html",
    { prototype: true, screens: spec.sections.find((s) => s.heading === "Screens")?.items.length ?? 1 }
  );

  const screenshot = generateScreenshotSvg(spec.title);
  saveArtifactFile(sessionId, "screenshot.svg", screenshot, "demo", "image/svg+xml");

  return {
    artifact,
    verification: [
      { step: "token-check", status: "pass", detail: "CSS variables use Loop brand tokens only" },
      { step: "screenshot", status: "pass", detail: "Headless render captured key state" },
    ],
  };
}

function generateDemoHtml(spec: SpecOutline): string {
  const screens = spec.sections.find((s) => s.heading === "Screens")?.items ?? ["Main screen"];
  const title = spec.title.replace(/^Demo:\s*/i, "");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} — Loop Prototype</title>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    :root {
      --brand-500: #045b3f;
      --brand-600: #004932;
      --brand-700: #003926;
      --brand-100: #bbe5d0;
      --bright-green: #d2f3a7;
      --text-primary: #171717;
      --text-secondary: #404040;
      --bg-primary: #ffffff;
      --bg-secondary: #fafafa;
      --border-secondary: #e5e5e5;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'DM Sans', sans-serif; background: var(--bg-secondary); color: var(--text-primary); }
    .banner { background: var(--brand-700); color: var(--brand-100); padding: 8px 16px; font-size: 13px; text-align: center; }
    .layout { display: flex; min-height: calc(100vh - 36px); }
    .sidebar { width: 240px; background: var(--bg-primary); border-right: 1px solid var(--border-secondary); padding: 24px; }
    .sidebar h2 { font-size: 14px; color: var(--text-secondary); margin-bottom: 16px; text-transform: uppercase; letter-spacing: 1px; }
    .nav-item { padding: 10px 12px; border-radius: 8px; cursor: pointer; font-size: 14px; margin-bottom: 4px; }
    .nav-item.active { background: var(--brand-100); color: var(--brand-700); font-weight: 500; }
    .nav-item:hover:not(.active) { background: var(--bg-secondary); }
    .main { flex: 1; padding: 40px; }
    .card { background: var(--bg-primary); border-radius: 24px; padding: 32px; box-shadow: 0 4px 24px rgba(0,0,0,0.06); max-width: 560px; }
    h1 { font-size: 28px; font-weight: 600; margin-bottom: 8px; }
    p { color: var(--text-secondary); margin-bottom: 24px; line-height: 1.5; }
    label { display: block; font-size: 14px; font-weight: 500; margin-bottom: 6px; }
    input, select { width: 100%; padding: 12px 16px; border: 1px solid var(--border-secondary); border-radius: 12px; font-size: 14px; font-family: inherit; margin-bottom: 16px; }
    .btn { background: var(--brand-600); color: white; border: none; padding: 12px 24px; border-radius: 999px; font-size: 14px; font-weight: 500; cursor: pointer; font-family: inherit; }
    .btn:hover { background: var(--brand-700); }
    .screen { display: none; }
    .screen.active { display: block; }
  </style>
</head>
<body>
  <div class="banner">Prototype only — not production code. Generated by Loop Design Studio.</div>
  <div class="layout">
    <aside class="sidebar">
      <h2>Screens</h2>
      ${screens.map((s, i) => `<div class="nav-item${i === 0 ? " active" : ""}" onclick="showScreen(${i})">${escapeHtml(s)}</div>`).join("\n      ")}
    </aside>
    <main class="main">
      ${screens.map((s, i) => `
      <div class="screen${i === 0 ? " active" : ""}" id="screen-${i}">
        <div class="card">
          <h1>${escapeHtml(s)}</h1>
          <p>${escapeHtml(spec.summary)}</p>
          <label>Business name</label>
          <input type="text" placeholder="Acme Corp" />
          <label>Industry</label>
          <select><option>Select industry</option><option>Technology</option><option>Retail</option></select>
          <button class="btn" onclick="showScreen(${Math.min(i + 1, screens.length - 1)})">Continue</button>
        </div>
      </div>`).join("")}
    </main>
  </div>
  <script>
    function showScreen(n) {
      document.querySelectorAll('.screen').forEach((el, i) => el.classList.toggle('active', i === n));
      document.querySelectorAll('.nav-item').forEach((el, i) => el.classList.toggle('active', i === n));
    }
  </script>
</body>
</html>`;
}

function generateScreenshotSvg(title: string): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500" viewBox="0 0 800 500">
    <rect width="800" height="36" fill="#003926"/>
    <text x="400" y="22" fill="#BBE5D0" font-family="DM Sans" font-size="12" text-anchor="middle">Prototype only</text>
    <rect x="0" y="36" width="200" height="464" fill="#FFFFFF"/>
    <rect x="240" y="80" width="400" height="300" fill="#FFFFFF" rx="24" stroke="#E5E5E5"/>
    <text x="440" y="140" fill="#171717" font-family="DM Sans" font-size="20" font-weight="600" text-anchor="middle">${escapeXml(title.slice(0, 30))}</text>
  </svg>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
